fixed source name for pyparsing and added more Python libs

diff --git a/Python/python3-tomli-opt/python3-tomli-opt.SlackBuild b/Python/python3-tomli-opt/python3-tomli-opt.SlackBuild
--- a/Python/python3-tomli-opt/python3-tomli-opt.SlackBuild
+++ b/Python/python3-tomli-opt/python3-tomli-opt.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# Slackware build script for python3-pyparsing
+# Slackware build script for python3-tomli-opt
 
-# Copyright 2025 Christopher Luck Orlando, FL
+# Copyright 2025  fourtysixandtwo <fourtysixandtwo@sliderr.net>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,12 +24,15 @@
 
 cd $(dirname $0) ; CWD=$(pwd)
 
-PRGNAM=python3-pyparsing
-SRCNAM=pyparsing
-VERSION=${VERSION:-3.2.5}
+PRGNAM=python3-tomli-opt
+SRCNAM=tomli
+VERSION=${VERSION:-2.2.1}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
+
+# set noarch because installing to /opt
+ARCH=noarch
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -39,9 +42,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -50,23 +50,6 @@ fi
 TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
-
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
-elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
-else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
-fi
 
 set -e
 
@@ -79,19 +62,29 @@ cd $SRCNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-## If your application only has a pyproject.toml:
-python3 -m build --wheel --no-isolation
-python3 -m installer --destdir "$PKG" dist/*.whl
+PYVER=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
+
+python3 -m flit_core.wheel
+python3 -m installer -d "$PKG" dist/*.whl
+
+if [ "$PKG/usr/" != "/usr/" ]; then
+  mkdir -p $PKG/opt
+  mv $PKG/usr/lib*/python$PYVER $PKG/opt/
+  rmdir $PKG/usr/lib*
+else
+  echo "ERROR: \$PKG is not set! We don't want to move the real /usr/lib*/python$PYVER"
+  exit 1
+fi
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a CHANGES CODE_OF_CONDUCT.rst CONTRIBUTING.md LICENSE PKG-INFO README.rst $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a LICENSE PKG-INFO README.* $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
