removed duplicate Python package.  Added packages to come in line with dev branch

diff --git a/Python/python3-setuptools-rust-opt/python3-setuptools-rust-opt.SlackBuild b/Python/python3-setuptools-rust-opt/python3-setuptools-rust-opt.SlackBuild
--- a/Python/python3-setuptools-rust-opt/python3-setuptools-rust-opt.SlackBuild
+++ b/Python/python3-setuptools-rust-opt/python3-setuptools-rust-opt.SlackBuild
@@ -1,8 +1,9 @@
 #!/bin/bash
 
-# Slackware build script for xemu
+# Slackware build script for python3-setuptools-rust-opt
 
-# Copyright 2024 Christopher Luck Orlando, FL
+# Copyright 2023-2025  fourtysixandtwo <fourtysixandtwo@sliderr.net>
+# Copyright 2021 Willy Sudiarto Raharjo <willysr@slackbuilds.org>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,11 +25,14 @@
 
 cd $(dirname $0) ; CWD=$(pwd)
 
-PRGNAM=xemu
-VERSION=${VERSION:-0.8.108}
+PRGNAM=python3-setuptools-rust-opt
+SRCNAM=setuptools_rust
+VERSION=${VERSION:-1.12.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
+
+ARCH=noarch
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
@@ -38,9 +42,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -50,62 +51,45 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
-if [ "$ARCH" = "i586" ]; then
-  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
-elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
-else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
-fi
-
 set -e
-# If you prefer to do selective error checking with
-#   command || exit 1
-# then that's also acceptable.
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-mkdir -p $PRGNAM-$VERSION
-tar xvf $CWD/src.tar.gz -C $PRGNAM-$VERSION
-cd $PRGNAM-$VERSION
+rm -rf $SRCNAM-$VERSION
+tar xvf $CWD/$SRCNAM-$VERSION.tar.gz
+cd $SRCNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
-./build.sh
+PYVER=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
+export PYTHONPATH=/opt/python$PYVER/site-packages/
 
-mkdir -p $PKG/usr/bin
-mkdir -p $PKG/usr/share/applications
+python3 -m build --no-isolation
+python3 -m installer -d "$PKG" dist/*.whl
 
-install -Dm 0755  dist/xemu $PKG/usr/bin/
-install -Dm 0644 ui/xemu.desktop $PKG/usr/share/applications/
-
-rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
+if [ "$PKG/usr/" != "/usr/" ]; then
+  mkdir -p $PKG/opt
+  mv $PKG/usr/lib*/python$PYVER $PKG/opt/
+  rmdir $PKG/usr/lib*
+else
+  echo "ERROR: \$PKG is not set! We don't want to move the real /usr/lib*/python$PYVE$PYVERR"
+  exit 1
+fi
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a COPYING* LICENSE MAINTAINERS README* $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a *.md $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
