version bumped setuptools-scm-opt and added new libraries needed.

diff --git a/Libraries/libslirp/libslirp.SlackBuild b/Libraries/libslirp/libslirp.SlackBuild
--- a/Libraries/libslirp/libslirp.SlackBuild
+++ b/Libraries/libslirp/libslirp.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# Slackware build script for python3-setuptools-scm-opt
+# Slackware build script for libslirp
 
-# Copyright 2023-2024  fourtysixandtwo <fourtysixandtwo@sliderr.net>
+# Copyright 2022-2024  Vijay Marcel
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,21 +24,17 @@
 
 cd $(dirname $0) ; CWD=$(pwd)
 
-PRGNAM=python3-setuptools-scm-opt
-SRCNAM=setuptools_scm
-VERSION=${VERSION:-9.2.2}
+PRGNAM=libslirp
+VERSION=${VERSION:-4.8.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
-# set noarch because installing to /opt
-ARCH=noarch
-
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) ARCH=i586 ;;
-    arm*) ARCH=arm ;;
-       *) ARCH=$( uname -m ) ;;
+    i?86) export ARCH=i586 ;;
+    arm*) export ARCH=arm ;;
+       *) export ARCH=$( uname -m ) ;;
   esac
 fi
 
@@ -51,41 +47,55 @@ TMP=${TMP:-/tmp/SBo}
 PKG=$TMP/package-$PRGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
+if [ "$ARCH" = "i586" ]; then
+  SLKCFLAGS="-march=i586 -mtune=i686 -pipe -O2 -fPIC"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-march=i686 -mtune=i686 -pipe -O2 -fPIC"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-march=x86-64 -mtune=generic -pipe -O2 -fPIC"
+  LIBDIRSUFFIX="64"
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
+fi
+
 set -e
+trap 'echo "$0 FAILED at line $LINENO!" | tee $OUTPUT/error-${PRGNAM}.log' ERR
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $SRCNAM-$VERSION
-tar xvf $CWD/$SRCNAM-$VERSION.tar.gz
-cd $SRCNAM-$VERSION
+rm -rf $PRGNAM-$VERSION
+rm -rf $PKG
+tar xvf $CWD/$PRGNAM-v$VERSION.tar.gz
+cd $PRGNAM-v$VERSION
+
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \+ -o \
+  -o -perm 511 \) -exec chmod 755 {} \; -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
 
-PYVER=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
-export PYTHONPATH=/opt/python$PYVER/site-packages
+CFLAGS="$SLKCFLAGS" \
+CXXFLAGS="$SLKCFLAGS" \
 
-python3 -m build --no-isolation
-python3 -m installer -d "$PKG" dist/*.whl
+meson build
+cd build
+meson configure -Dprefix=/usr
+DESTDIR=$PKG ninja  install
+cd ..
 
-if [ "$PKG/usr/" != "/usr/" ]; then
-  mkdir -p $PKG/opt
-  mv $PKG/usr/lib*/python$PYVER $PKG/opt/
-  rmdir $PKG/usr/lib*
-else
-  echo "ERROR: \$PKG is not set! We don't want to move the real /usr/lib*/python$PYVER"
-  exit 1
-fi
+# Don't ship .la files:
+rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
 
-find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
-  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" \
+  | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded --remove-section=.comment --remove-section=.note 2> /dev/null || true
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a CHANGELOG.md LICENSE README.md PKG-INFO $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a CHANGELOG.md COPYRIGHT README.md  $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
