version bumped CrealityPrint and LIEF.  Added assimp

diff --git a/Libraries/assimp/assimp.SlackBuild b/Libraries/assimp/assimp.SlackBuild
--- a/Libraries/assimp/assimp.SlackBuild
+++ b/Libraries/assimp/assimp.SlackBuild
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-# Slackware build script for CrealityPrint
+# Slackware build script for assimp
 
-# Copyright 2023 Christopher Luck Orlando, FL
+# Copyright 2014-2016  Dimitris Zlatanidis  Orestiada, Greece
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -24,9 +24,9 @@
 
 cd $(dirname $0) ; CWD=$(pwd)
 
-PRGNAM=CrealityPrint
-VERSION=${VERSION:-6.2.0}
-BUILD=${BUILD:-1}
+PRGNAM=assimp
+VERSION=${VERSION:-5.0.1}
+BUILD=${BUILD:-4}
 TAG=${TAG:-_SBo}
 PKGTYPE=${PKGTYPE:-tgz}
 
@@ -38,9 +38,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-# If the variable PRINT_PACKAGE_NAME is set, then this script will report what
-# the name of the created package would be, and then exit. This information
-# could be useful to other scripts.
 if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
   echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
   exit 0
@@ -59,15 +56,12 @@ elif [ "$ARCH" = "i686" ]; then
 elif [ "$ARCH" = "x86_64" ]; then
   SLKCFLAGS="-O2 -fPIC"
   LIBDIRSUFFIX="64"
-elif [ "$ARCH" = "aarch64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
 else
   SLKCFLAGS="-O2"
   LIBDIRSUFFIX=""
 fi
 
-set -e # Exit on most errors
+set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
@@ -78,51 +72,43 @@ cd $PRGNAM-$VERSION
 chown -R root:root .
 find -L . \
  \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
+  -o -perm 511 \) -exec chmod 755 {} \+ -o \
  \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \+
 
+# 20250614 KEC: gcc-15 compatibility.
+patch -p0 < $CWD/gcc-15.patch
+
+# 20250330 KEC: Added POLICY_VERSION_MINIMUM for cmake compatibility.
 mkdir -p build
 cd build
   cmake \
     -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
     -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
     -DCMAKE_INSTALL_PREFIX=/usr \
-    -DLIB_SUFFIX=${LIBDIRSUFFIX} \
-    -DOPENMP_ROOT=usr/lib64/cmake/openmp/ \
+    -DASSIMP_LIB_INSTALL_DIR=/usr/lib${LIBDIRSUFFIX} \
+    -DASSIMP_BUILD_TESTS=OFF \
     -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
-    -DMAN_INSTALL_DIR=/usr/man \
     -DCMAKE_BUILD_TYPE=Release ..
   make
-  make install/strip DESTDIR=$PKG
+  make install DESTDIR=$PKG
 cd ..
-
-# Don't ship .la files:
-rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
 
 find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
 
-#find $PKG/usr/man -type f -exec gzip -9 {} \;
-#for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
-
-# Compress info pages and remove the package's dir file
-# If no info pages are installed by the software, don't leave this in the script
-#rm -f $PKG/usr/info/dir
-#gzip -9 $PKG/usr/info/*.info*
-
-# Remove perllocal.pod and other special files that don't need to be installed,
-# as they will overwrite what's already on the system.  If this is not needed,
-# remove it from the script.
-#find $PKG -name perllocal.pod -o -name ".packlist" -o -name "*.bs" | xargs rm -f || true
+# 20220214 bkw: fix broken cmake support on x86_64. this was causing
+# ogre to fail to build (and probably other stuff that uses this).
+[ -n "$LIBDIRSUFFIX" ] && \
+  sed -i "s,\\<lib\\>,lib$LIBDIRSUFFIX,g" \
+  $PKG/usr/lib$LIBDIRSUFFIX/cmake/$PRGNAM-*/*
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cp -a *.md LICENSE $PKG/usr/doc/$PRGNAM-$VERSION
+cp -a CHANGES CREDITS LICENSE README *.md $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
-#cat $CWD/doinst.sh > $PKG/install/doinst.sh
 
 cd $PKG
 /sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
